In [12]:
import numpy as np
ch_arr2=np.array(["supervised","unsuervised","semi-supervised"])
low_arr2=np.char.lower(ch_arr2)
low_arr2

array(['supervised', 'unsuervised', 'semi-supervised'], dtype='<U15')

In [13]:
cleand_arr=np.char.replace(low_arr2,"-","_")
cleand_arr

array(['supervised', 'unsuervised', 'semi_supervised'], dtype='<U15')

In [18]:
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [19]:
arr.dtype

dtype('int64')

In [20]:
ch_arr2.dtype

dtype('<U15')

In [41]:
arr1=np.array([1,2,3,4,5],dtype='f')
arr1

array([1., 2., 3., 4., 5.], dtype=float32)

In [37]:
arr=arr1.astype('S')
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [38]:
ar=arr.astype('i')
ar

array([1, 2, 3, 4, 5], dtype=int32)

In [43]:
are2=np.zeros(3)
are2

array([0., 0., 0.])

In [46]:
are2=np.ones(3)
are2

array([1., 1., 1.])

In [57]:
are2=np.random.random(3)
are2

array([0.40298059, 0.93171503, 0.92129496])

In [52]:
are2=np.zeros((2,2),dtype=int)
are2

array([[0, 0],
       [0, 0]])

In [54]:
are2=np.random.random((2,2))
are2

array([[0.91752372, 0.92874746],
       [0.44870401, 0.33630579]])

In [60]:
are2=np.ones((1,2,3),dtype=int)
are2

array([[[1, 1, 1],
        [1, 1, 1]]])

In [78]:
a1=np.array([[1,2,3],[1,2,0]])
a2=np.array([[1,2,3],[2,1,0]])
a3=np.power(a1,a2)
a3

array([[ 1,  4, 27],
       [ 1,  2,  1]])

In [82]:
ar=np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a=np.random.randint(low=1,high=5,size=10)
a

array([1, 1, 1, 4, 3, 4, 3, 2, 3, 4], dtype=int32)

In [92]:
aa=np.concatenate([a,ar])
aa

array([1, 1, 1, 4, 3, 4, 3, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
flat=a1.flatten()
flat

array([1, 2, 3, 1, 2, 0])

In [97]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [98]:
import matplotlib.pyplot as plt
from scipy import stats


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "C:\ProgramData\anaconda3\Lib\site-packa

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import